version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  #       # run tests!
  #       - run: npm run lint
  #       - run: npm test

  deploy-job:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: sudo apt-get install awscli
      - run: npm build
      - run:
          name: Deploy to S3 if tests pass and branch is master
          command: aws s3 sync build/ s3://env-test  --delete --region eu-west-2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
